language: python
python:
  - "2.7"
env:
  - BILLY_UNIT_TEST_DB=sqlite:// BILLY_FUNC_TEST_DB=sqlite://
  - BILLY_TEST_ALEMBIC=1 BILLY_UNIT_TEST_DB=postgresql://postgres:@127.0.0.1/billy BILLY_FUNC_TEST_DB=postgresql://postgres:@127.0.0.1/billy
  - BILLY_TEST_INTEGRATION=1
# command to install dependencies
install: 
  - "pip install psycopg2 --use-mirrors"
  - "pip install flake8 --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -r test_requirements.txt --use-mirrors"
  - "python setup.py develop"
before_script: 
  - "psql -c 'create database billy;' -U postgres"
  - "flake8 billy --ignore=E501,W291,W293"
# command to run tests
script: 
  - 'if [ -z "$BILLY_TEST_INTEGRATION" ]; then'
  - '    python setup.py nosetests'
  - 'else'
  - '    initialize_billy_db test.ini'
  - '    pserve test.ini --daemon'
  - '    nosetests billy/tests/integration --verbosity=2'
  - 'fi'
